title: Corey Lurvey
description: Full-stack software engineer based in Bristol, UK
contact:
  - email: `mailto:corey@lurvey.dev`
    linkedIn: https://www.linkedin.com/in/coreylurvey/
    github: https://github.com/coreylurvey/
